import "./CV.css"

export const cv = {
    hero: {
      name: "David",
      surname: "Boeru",
      city: "Avengers Tower / New York",
      email: "beniboeru702@gmail.com",
      birthDate: "12/02/1999",
      phone: "(+40) 767333841 ",
      image: "https://e.rpp-noticias.io/large/2016/01/25/301630_68611.jpg",
      gitHub: "https://github.com/DavidBoeru",
      aboutMe: [
        {
          info: "🤖Mi armadura, nunca fue una distracción ni un pasatiempo, fue un capullo. Yo soy Iron Man.",
        },
        {
          info: "🔩 Director ejecutivo de Industrias Stark.",
        },
        {
          info: "🕶 Genio, multimillonario, playboy, filántropo",
        },
        {
          info: "🦾Tengo la responsabilidad de mantener mis inventos lejos de manos del mal, pero tengo una responsabilidad mayor de oponerme a ese mal en cualquier forma que pueda. ",
        },
      ],
    },
    education: [
      {
        name: "Master in physics",
        date: "1985",
        where: "MIT",
      },
      {
        name: "Aeronautical Engineering",
        date: "1995",
        where: "ATI Vaughn College",
      },
      {
        name: "Weapons Engineer",
        date: "1998",
        where: "Firearm Collegue, Queens",
      },
    ],
    experience: [
      {
        name: "Consultant",
        date: "01/01/2013 – Nowadays",
        where: "S.H.I.E.L.D",
        description:
          "It builds the helicarriers used by S.H.I.E.L.D. It produces the Quinjets used by the Avengers.",
      },
      {
        name: "CEO",
        date: "01/01/2000 – 28/02/2012",
        where: "Stark Industries",
        description:
          "Manage the company, which is a multi-billion dollar multinational corporation that develops and manufactures advanced weapon and defense technologies. The company manufactures the armor worn by Iron Man and War Machine.",
      },
    ],
    languages: {
      language: "English",
      wrlevel: "Native",
      splevel: "Native",
    },
    habilities: [
      "Robotics",
      "Robot Programming",
      "Physics",
      "Weaponery",
      "Engineer",
      "Money",
      "Dating",
      "Saving the world",
    ],
    volunteer: [
      {
        name: "September Foundation",
        where: "MIT",
        description:
          "The September Foundation is a program by Tony Stark to fund schools and young prodigies in their education. The foundation was named by Stark after a lyric from The Fantasticks song, 'Try to Remember,' which he heard his mother sing and play on the piano before her death.",
      },
      {
        name: "Damage Control",
        where: "U.S.A.",
        description:
          "The United States Department of Damage Control, occasionally known as the DODC, is a department of the United States of America. Initially a subsidiary of S.H.I.E.L.D., Damage Control was an organization specializing in post-battle clean-up. Following the Battle of New York, Damage Control was made into an executive branch of the United States government, and in a joint venture with Stark Industries, was tasked with acquiring alien and other dangerous artifacts along with cleaning up damages caused by enhanced individuals.",
      },
    ],
  };